server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  ssl:
    bundle:
      jks:
        demo-client:
          key:
            alias: demo-client-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
        self-signed-demo-client:
          key:
            alias: self-signed-demo-client-sample
            password: password
          keystore:
            location: classpath:keystore-self-signed.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore-self-signed.p12
            password: password
            type: PKCS12
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: messaging-client-oidc
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: message.read,message.write
            client-name: messaging-client-authorization-code
          messaging-client-client-credentials:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: messaging-client-client-credentials
          user-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: user.read
            client-name: user-client-authorization-code
          messaging-client-device-code:
            provider: spring
            client-id: device-messaging-client
            client-authentication-method: none
            authorization-grant-type: urn:ietf:params:oauth:grant-type:device_code
            scope: message.read,message.write
            client-name: messaging-client-device-code
          mtls-demo-client-client-credentials:
            provider: spring-tls
            client-id: mtls-demo-client
            client-authentication-method: tls_client_auth
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: mtls-demo-client-client-credentials
          mtls-self-signed-demo-client-client-credentials:
            provider: spring-tls
            client-id: mtls-demo-client
            client-authentication-method: self_signed_tls_client_auth
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: mtls-self-signed-demo-client-client-credentials
        provider:
          spring:
            issuer-uri: http://localhost:9000
          spring-tls:
            token-uri: https://localhost:9443/oauth2/token

messages:
  base-uri: https://127.0.0.1:8443/messages

user-messages:
  base-uri: http://127.0.0.1:8091/user/messages
